
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clo835-role-binding 
  namespace: final
subjects:
- kind: ServiceAccount 
  name: clo835
  namespace: final
roleRef:
  kind: Role
  name: clo835-role
  apiGroup: rbac.authorization.k8s.io
